---

- hosts: all
  vars:
    servernummer: "2"
    network_ipv4: "10.207.16"
    network_ipv6: "fd01:67c:770:2000::"
    network_ipv6_public: "2a0e:b107:1901:1000::"
  roles:
    - role: geerlingguy.ntp
      ntp_enabled: true
      ntp_timezone: Europe/Berlin
      ntp_manage_config: true
      ntp_servers:
        - 0.de.pool.ntp.org
        - 1.de.pool.ntp.org
        - 2.de.pool.ntp.org
        - 3.de.pool.ntp.org
      ntp_restrict:
        - "127.0.0.1"
        - "::1"

    - role: batmancompile
      batman_adv_number: 2019.3

    - role: network
    - role: pdns-recursor
    - role: dhcpd
      dhcpd_ipv4_max: "10.207.23.254"
      dhcpd_ipv6_max: "fd01:67c:770:2fff:ffff:ffff:ffff"
      # Which IPV4 Blocks should be ignored?
      dhcpd_ipv4_blockstart1: "10.207.0.0"
      dhcpd_ipv4_blockend1: "10.207.15.255"
      dhcpd_ipv4_blockstart2: "10.207.24.0"
      dhcpd_ipv4_blockend2: "10.207.255.255"

    - role: fastd
      fastd_privatekey: secret

    - role: wireguard
      wireguard_privatekey_node1: <insert your wireguard privatekey for connection to node1 IPV6 via FFRheinland>
      wireguard_privatekey_nodes: <insert your wireguard privatekey for the node connection>
      wireguard_privatekey_backbone: <insert your wireguard privatekey for the backend between the supernodes>
      wireguard_nginx_port: <port 80 or 443. If you use 443, the port must be reachable from the internet to generate a lets encrypt certificate! If you insert port 80, some proxy in front must handle
    the  https request>

    - role: openvpn
      openvpn_clientname: user
      openvpn_clientpass: pass

