---

- hosts: all
  vars:
    servernummer: "1"
    network_ipv4: "10.207.8"
    network_ipv6: "fd01:67c:770:1000::"
    network_ipv6_public: "2a0e:b107:1901::"
  roles:
    - role: geerlingguy.ntp
      ntp_enabled: true
      ntp_timezone: Europe/Berlin
      ntp_manage_config: true
      ntp_servers:
        - 0.de.pool.ntp.org
        - 1.de.pool.ntp.org
        - 2.de.pool.ntp.org
        - 3.de.pool.ntp.org
      ntp_restrict:
        - "127.0.0.1"
        - "::1"

    - role: batmancompile
      batman_adv_number: 2019.3

    - role: network
    - role: pdns-recursor
    - role: dhcpd
      dhcpd_ipv4_max: "10.207.15.254"
      dhcpd_ipv6_max: "fd01:67c:770:1fff:ffff:ffff:ffff"
      # Which IPV4 Blocks should be ignored?
      dhcpd_ipv4_blockstart1: "10.207.0.0"
      dhcpd_ipv4_blockend1: "10.207.7.255"
      dhcpd_ipv4_blockstart2: "10.207.16.0"
      dhcpd_ipv4_blockend2: "10.207.255.255"

    - role: fastd
      fastd_privatekey: secret

    - role: openvpn
      openvpn_clientname: user
      openvpn_clientpass: pass

